language: php

dist: xenial

services:
  - mysql
  - postgresql

env:
  global:
    - COMPOSER_ROOT_VERSION="4.0.x-dev"

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL PHPUNIT_TEST=1 RECIPE_VERSION="^1 --prefer-lowest"
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1 RECIPE_VERSION="^1"
    - php: 7.1
      env: DB=PGSQL PHPUNIT_TEST=1 RECIPE_VERSION="^4 --prefer-lowest"
    - php: 7.2
      env: DB=PGSQL PHPUNIT_COVERAGE_TEST=1 RECIPE_VERSION="^4"
    - php: 7.3
      env: DB=PGSQL PHPCS_TEST=1 PHPUNIT_TEST=1 RECIPE_VERSION="4.x-dev"

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - composer require --no-update silverstripe/userforms:5.x-dev silverstripe/recipe-cms:$RECIPE_VERSION
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:^2; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs code/ tests/ ; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
